services:
  megu-chat-db-api:
    container_name: megu-chat-db-api
    build:
      context: ../../apps/db-api
      dockerfile: Dockerfile
      no_cache: true
    env_file:
      - ../../apps/db-api/.env.local.docker
    ports:
      - '8000:8000'
    networks:
      - meguchat-network
    depends_on:
      postgres-primary:
        condition: service_healthy
      backend-migrations:
        condition: service_completed_successfully
