from dotenv import load_dotenv
import os

load_dotenv(".env.dev")

PRIMARY_DB_USER = os.getenv("PRIMARY_DATABASE_USER")
PRIMARY_DB_PASSWORD = os.getenv("PRIMARY_DATABASE_PASSWORD")
PRIMARY_DB_HOST = os.getenv("PRIMARY_DATABASE_HOST")
PRIMARY_DB_PORT = os.getenv("PRIMARY_DATABASE_PORT")
PRIMARY_DB_NAME = os.getenv("PRIMARY_DATABASE_NAME")

PRIMARY_DB_STRING = (
    f"postgresql+psycopg://{PRIMARY_DB_USER}:{PRIMARY_DB_PASSWORD}"
    f"@{PRIMARY_DB_HOST}:{PRIMARY_DB_PORT}/{PRIMARY_DB_NAME}"
)

REPLICA_DB_USER = os.getenv("REPLICA_DATABASE_USER")
REPLICA_DB_PASSWORD = os.getenv("REPLICA_DATABASE_PASSWORD")
REPLICA_DB_HOST = os.getenv("REPLICA_DATABASE_HOST")
REPLICA_DB_PORT = os.getenv("REPLICA_DATABASE_PORT")
REPLICA_DB_NAME = os.getenv("REPLICA_DATABASE_NAME")

REPLICA_DB_STRING = (
    f"postgresql+psycopg://{REPLICA_DB_USER}:{REPLICA_DB_PASSWORD}"
    f"@{REPLICA_DB_HOST}:{REPLICA_DB_PORT}/{REPLICA_DB_NAME}"
)
