name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      PRIMARY_DATABASE_USER: meguchat
      PRIMARY_DATABASE_PASSWORD: meguchat
      PRIMARY_DATABASE_HOST: localhost
      PRIMARY_DATABASE_PORT: 5433
      PRIMARY_DATABASE_NAME: meguchat
      REPLICA_DATABASE_USER: meguchat
      REPLICA_DATABASE_PASSWORD: meguchat
      REPLICA_DATABASE_HOST: localhost
      REPLICA_DATABASE_PORT: 5434
      REPLICA_DATABASE_NAME: meguchat
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/docs/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e"

      # Cache node_modules
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 'latest'

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Install Node dependencies
        run: npm ci

      - name: Start Docker Compose
        working-directory: infra/postgres
        run: docker compose -f docker-compose.yaml up -d

      - name: Wait for Postgres to be ready
        working-directory: infra/postgres
        run: |
          echo "Waiting for Postgres to be ready..."
          until docker exec postgres-primary pg_isready -U meguchat -d meguchat; do
            sleep 1
          done
          echo "Postgres is ready!"

      - name: Apply db-api database schema
        run: npx nx run db-api:migrate

      # Prepend any command with "nx record --" to record its logs to Nx Cloud
      - run: npx nx record -- npx nx format:check --base="remotes/origin/main"
      - run: npx nx run-many -t lint test build typecheck e2e
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/docs/features/ci-features/self-healing-ci
      - run: npx nx fix-ci
        if: always()

      - name: Stop Docker Compose
        working-directory: infra/postgres
        if: always()
        run: docker compose -f docker-compose.yaml down -v
